org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false

# Enable R8 Full Mode for higher optimization, shrinking, and obfuscation percentage (>25%)
android.enableR8.fullMode=true