// File generated by Antigravity from google-services.json.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHagT69yAb_4jtGd1Ax0koefDASXY3kbs',
    appId: '1:283030564600:android:6dabf65a54ff5998ae950d',
    messagingSenderId: '283030564600',
    projectId: 'quizs-arknox-app',
    storageBucket: 'quizs-arknox-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQs4ewyGia1xG_GA6yoMpwIaKOtX0O9nI',
    appId: '1:317616672617:web:2db75cd24691057041b7f8',
    messagingSenderId: '317616672617',
    projectId: 'quizs-5b40a',
    storageBucket: 'quizs-5b40a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQs4ewyGia1xG_GA6yoMpwIaKOtX0O9nI',
    appId: '1:317616672617:ios:2db75cd24691057041b7f8',
    messagingSenderId: '317616672617',
    projectId: 'quizs-5b40a',
    storageBucket: 'quizs-5b40a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQs4ewyGia1xG_GA6yoMpwIaKOtX0O9nI',
    appId: '1:317616672617:ios:2db75cd24691057041b7f8',
    messagingSenderId: '317616672617',
    projectId: 'quizs-5b40a',
    storageBucket: 'quizs-5b40a.firebasestorage.app',
  );
}
