import 'package:flutter/material.dart';

import '../widgets/design_widgets.dart';

class QuestionScreen extends StatelessWidget {
  const QuestionScreen({super.key, this.explanation = false});
  final bool explanation;

  @override
  Widget build(BuildContext context) => DesignCanvas(
    adAfter: explanation ? 811 : 738,
    topColor: const Color(0xFF31005C),
    children: [
      const Positioned.fill(child: QuestionBackground()),
      label(
        'Quizs',
        159,
        24,
        32,
        color: Colors.white,
        family: 'Quizlo',
        lineHeight: 1.44,
      ),
      backButton(context, compact: true),
      panel(59, 131, 294, 416, const Color(0xFF9C34F7), radius: 18),
      panel(51, 125, 310, 416, const Color(0xFFD7AAFF), radius: 18),
      panel(46, 117, 320, 416, Colors.white, radius: 22),
      label(
        'Questions',
        70,
        132,
        20,
        family: 'Questrial',
        color: const Color(0x52000000),
        lineHeight: 1.1,
      ),
      label(
        'Which planet is known as\nthe Red Planet?',
        70,
        159,
        20,
        width: 280,
        weight: FontWeight.w600,
        lineHeight: 1.25,
      ),
      for (var i = 0; i < 4; i++) ...[
        panel(
          84,
          [265.0, 324.0, 382.0, 440.0][i],
          243,
          i == 0 ? 49 : 48,
          i == 2 ? const Color(0xFF8CE7BA) : Colors.white,
          radius: 9,
          border: i == 2 ? const Color(0xFF1ACE50) : const Color(0xFFEDEDED),
        ),
        label(
          ['Venus', 'Mercury', 'Mars', 'Jupiter'][i],
          i == 0 ? 102 : 101,
          [277.0, 335.0, 393.0, 451.0][i],
          20,
          weight: FontWeight.w600,
          lineHeight: 1.25,
        ),
        action(
          context,
          'View answer explanation for ${['Venus', 'Mercury', 'Mars', 'Jupiter'][i]}',
          '/explanation',
          84,
          [265.0, 324.0, 382.0, 440.0][i],
          243,
          48,
        ),
      ],
      asset('7-63_imgEllipse3.svg', 283, 392, 28, 28),
      asset('7-63_imgCheck2.png', 287, 396, 21, 21, color: Colors.white),
      label(
        'Previous',
        57,
        561,
        14,
        color: Colors.white,
        weight: FontWeight.w600,
        lineHeight: 1.25,
      ),
      label(
        'Next',
        321,
        561,
        14,
        color: Colors.white,
        weight: FontWeight.w600,
        lineHeight: 1.25,
      ),
      action(
        context,
        'Previous question',
        explanation ? '/question' : '/mathematics',
        45,
        546,
        95,
        44,
      ),
      action(
        context,
        'Next question',
        explanation ? '/results' : '/explanation',
        302,
        546,
        65,
        44,
      ),
      if (explanation) ...[
        panel(58, 592, 294, 137, Colors.white, radius: 12),
        panel(73, 625, 70, 70, const Color(0xFF109E3B), radius: 6),
        label(
          'Mars- The red planet',
          156,
          611,
          14,
          weight: FontWeight.w700,
          lineHeight: 1.25,
        ),
        label(
          'Mars is the fourth planet from the\nSun and is known as the Red Planet\nbecause of iron-rich dust on its\nsurface. It has a thin atmosphere,\nrocky terrain, giant volcanoes, deep\nvalleys, and two small moons—Phobos\nand Deimos.',
          157,
          636,
          8,
          width: 168,
          weight: FontWeight.w600,
          lineHeight: 1.25,
        ),
      ],
      panel(
        explanation ? 56 : 57,
        explanation ? 752 : 678,
        298,
        7,
        const Color(0xFF8A00E5),
        radius: 22,
      ),
      panel(
        explanation ? 56 : 57,
        explanation ? 752 : 678,
        127,
        7,
        const Color(0xFF00FF96),
        radius: 22,
      ),
      label(
        'Next Trial in 5s',
        explanation ? 64 : 65,
        explanation ? 780 : 706,
        14,
        color: Colors.white,
        weight: FontWeight.w600,
        lineHeight: 1.25,
      ),
      panel(
        explanation ? 193 : 194,
        explanation ? 772 : 699,
        152,
        33,
        const Color(0xFF4FE59A),
        radius: 6,
      ),
      asset(
        '7-63_imgMaskGroup.svg',
        explanation ? 193 : 194,
        explanation ? 772 : 698,
        152,
        33,
      ),
      label(
        'Next Trial',
        explanation ? 231 : 232,
        explanation ? 779 : 706,
        15,
        color: Colors.white,
        weight: FontWeight.w800,
        lineHeight: 1.25,
      ),
      action(
        context,
        'Next Trial',
        '/results',
        explanation ? 190 : 191,
        explanation ? 767 : 694,
        158,
        44,
      ),
    ],
  );
}
